name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Develop with Main
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          git switch origin develop
          git pull origin main
          git push origin develop

  # build-and-upload:
  #   name: Build and Upload
  #   runs-on: ubuntu-latest
  #   needs: release
  #   steps:
  #     - name: Echo
  #       run: echo "Build and Upload!!"

  # pipeline:
  #   name: Pipeline
  #   runs-on: ubuntu-latest
  #   needs: build-and-upload
  #   steps:
  #     - name: Echo
  #       run: echo "Pipeline!!"
